// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.13.0
// source: user_pr.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PrPsLogin_Result int32

const (
	PrPsLogin_OK      PrPsLogin_Result = 0 // 成功
	PrPsLogin_INVALID PrPsLogin_Result = 1 // 无效用户
)

// Enum value maps for PrPsLogin_Result.
var (
	PrPsLogin_Result_name = map[int32]string{
		0: "OK",
		1: "INVALID",
	}
	PrPsLogin_Result_value = map[string]int32{
		"OK":      0,
		"INVALID": 1,
	}
)

func (x PrPsLogin_Result) Enum() *PrPsLogin_Result {
	p := new(PrPsLogin_Result)
	*p = x
	return p
}

func (x PrPsLogin_Result) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PrPsLogin_Result) Descriptor() protoreflect.EnumDescriptor {
	return file_user_pr_proto_enumTypes[0].Descriptor()
}

func (PrPsLogin_Result) Type() protoreflect.EnumType {
	return &file_user_pr_proto_enumTypes[0]
}

func (x PrPsLogin_Result) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PrPsLogin_Result.Descriptor instead.
func (PrPsLogin_Result) EnumDescriptor() ([]byte, []int) {
	return file_user_pr_proto_rawDescGZIP(), []int{2, 0}
}

type LoginReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account string `protobuf:"bytes,1,opt,name=account,proto3" json:"account"` //域账号
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_pr_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_pr_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_user_pr_proto_rawDescGZIP(), []int{0}
}

func (x *LoginReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

type LoginRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Passport int32  `protobuf:"varint,1,opt,name=passport,proto3" json:"passport"` // 用户在数据库中的ID
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`          // 名称
	Role     string `protobuf:"bytes,3,opt,name=role,proto3" json:"role"`          // 用户角色(wms_manager:揽月管理员)
}

func (x *LoginRsp) Reset() {
	*x = LoginRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_pr_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRsp) ProtoMessage() {}

func (x *LoginRsp) ProtoReflect() protoreflect.Message {
	mi := &file_user_pr_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRsp.ProtoReflect.Descriptor instead.
func (*LoginRsp) Descriptor() ([]byte, []int) {
	return file_user_pr_proto_rawDescGZIP(), []int{1}
}

func (x *LoginRsp) GetPassport() int32 {
	if x != nil {
		return x.Passport
	}
	return 0
}

func (x *LoginRsp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LoginRsp) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type PrPsLogin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Req    *LoginReq        `protobuf:"bytes,1,opt,name=req,proto3" json:"req"`
	Rsp    *LoginRsp        `protobuf:"bytes,2,opt,name=rsp,proto3" json:"rsp"`
	Result PrPsLogin_Result `protobuf:"varint,3,opt,name=result,proto3,enum=jj.wms.PrPsLogin_Result" json:"result"` // 结果
}

func (x *PrPsLogin) Reset() {
	*x = PrPsLogin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_pr_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrPsLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrPsLogin) ProtoMessage() {}

func (x *PrPsLogin) ProtoReflect() protoreflect.Message {
	mi := &file_user_pr_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrPsLogin.ProtoReflect.Descriptor instead.
func (*PrPsLogin) Descriptor() ([]byte, []int) {
	return file_user_pr_proto_rawDescGZIP(), []int{2}
}

func (x *PrPsLogin) GetReq() *LoginReq {
	if x != nil {
		return x.Req
	}
	return nil
}

func (x *PrPsLogin) GetRsp() *LoginRsp {
	if x != nil {
		return x.Rsp
	}
	return nil
}

func (x *PrPsLogin) GetResult() PrPsLogin_Result {
	if x != nil {
		return x.Result
	}
	return PrPsLogin_OK
}

var File_user_pr_proto protoreflect.FileDescriptor

var file_user_pr_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x06, 0x6a, 0x6a, 0x2e, 0x77, 0x6d, 0x73, 0x22, 0x24, 0x0a, 0x08, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x4e, 0x0a,
	0x08, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x73, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73,
	0x73, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x73,
	0x73, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x22, 0xa4, 0x01,
	0x0a, 0x09, 0x50, 0x72, 0x50, 0x73, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x22, 0x0a, 0x03, 0x72,
	0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6a, 0x6a, 0x2e, 0x77, 0x6d,
	0x73, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x52, 0x03, 0x72, 0x65, 0x71, 0x12,
	0x22, 0x0a, 0x03, 0x72, 0x73, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6a,
	0x6a, 0x2e, 0x77, 0x6d, 0x73, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x73, 0x70, 0x52, 0x03,
	0x72, 0x73, 0x70, 0x12, 0x30, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x6a, 0x6a, 0x2e, 0x77, 0x6d, 0x73, 0x2e, 0x50, 0x72, 0x50,
	0x73, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x1d, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x4e, 0x56, 0x41, 0x4c,
	0x49, 0x44, 0x10, 0x01, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_user_pr_proto_rawDescOnce sync.Once
	file_user_pr_proto_rawDescData = file_user_pr_proto_rawDesc
)

func file_user_pr_proto_rawDescGZIP() []byte {
	file_user_pr_proto_rawDescOnce.Do(func() {
		file_user_pr_proto_rawDescData = protoimpl.X.CompressGZIP(file_user_pr_proto_rawDescData)
	})
	return file_user_pr_proto_rawDescData
}

var file_user_pr_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_user_pr_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_user_pr_proto_goTypes = []interface{}{
	(PrPsLogin_Result)(0), // 0: jj.wms.PrPsLogin.Result
	(*LoginReq)(nil),      // 1: jj.wms.LoginReq
	(*LoginRsp)(nil),      // 2: jj.wms.LoginRsp
	(*PrPsLogin)(nil),     // 3: jj.wms.PrPsLogin
}
var file_user_pr_proto_depIdxs = []int32{
	1, // 0: jj.wms.PrPsLogin.req:type_name -> jj.wms.LoginReq
	2, // 1: jj.wms.PrPsLogin.rsp:type_name -> jj.wms.LoginRsp
	0, // 2: jj.wms.PrPsLogin.result:type_name -> jj.wms.PrPsLogin.Result
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_user_pr_proto_init() }
func file_user_pr_proto_init() {
	if File_user_pr_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_user_pr_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_pr_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_pr_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrPsLogin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_user_pr_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_pr_proto_goTypes,
		DependencyIndexes: file_user_pr_proto_depIdxs,
		EnumInfos:         file_user_pr_proto_enumTypes,
		MessageInfos:      file_user_pr_proto_msgTypes,
	}.Build()
	File_user_pr_proto = out.File
	file_user_pr_proto_rawDesc = nil
	file_user_pr_proto_goTypes = nil
	file_user_pr_proto_depIdxs = nil
}
