// Code generated by protoc-gen-go-procedure. DO NOT EDIT.

package pb

import (
	gorm "gorm.io/gorm"
)

type UserProcedure interface {
	GetRawDB() *gorm.DB
	PrPsLogin(*LoginReq) ([]*LoginRsp, int, int, error)
}

type User_Procedure struct {
	db *gorm.DB
}

func NewUserProcedure(db *gorm.DB) UserProcedure {
	return &User_Procedure{db: db}
}

func (r *User_Procedure) GetRawDB() *gorm.DB {
	return r.db
}

func (r *User_Procedure) PrPsLogin(req *LoginReq) ([]*LoginRsp, int, int, error) {
	res := []*LoginRsp{}
	result := -1
	total := 0
	tx := r.db.Begin()
	err := tx.
		Raw("call pr_ps_login(@ov_return, ?, @ov_total_count)",
			req.Account).
		Scan(&res).
		Raw("select @ov_return").
		Scan(&result).
		Raw("select @ov_total_count").
		Scan(&total).
		Error

	if err != nil {
		tx.Rollback()
	} else {
		err = tx.Commit().Error
	}

	return res, result, total, err
}
