// Code generated by protoc-gen-jjpms. DO NOT EDIT.
// source: user_pr.proto

package pb

import (
	"gorm.io/gorm"
)

type UserProcedure interface {
	GetRawDB() *gorm.DB
	PrPsLogin(req *LoginReq) ([]*LoginRsp, int, error)
}
type User_Procedure struct {
	db *gorm.DB
}

func NewUserProcedure(db *gorm.DB) UserProcedure {
	return &User_Procedure{
		db: db,
	}
}

func (r *User_Procedure) GetRawDB() *gorm.DB {
	return r.db
}

func (r *User_Procedure) PrPsLogin(req *LoginReq) ([]*LoginRsp, int, error) {
	res := []*LoginRsp{}
	result := -1

	err := r.db.
		Raw("call pr_ps_login(@ov_return, ?)",
			req.Account).
		Scan(&res).
		Raw("select @ov_return").
		Scan(&result).
		Error

	return res, result, err
}
