// Code generated by protoc-gen-go-router. DO NOT EDIT.
package pb

import (
	context "context"
	runtime "github.com/devil-dwj/go-wms/api/runtime"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

type UserServerHandler interface {
	Login(context.Context, *LoginReq) (*LoginRsp, error)
	Info(context.Context, *emptypb.Empty) (*LoginRsp, error)
}

func RegisterUserRouter(s runtime.RouterRegistrar, srv UserServerHandler) {
	s.RegisterRouter(&UserRouter_Desc, srv)
}

func _UserRouter_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(LoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	return srv.(UserServerHandler).Login(ctx, in)
}

func _UserRouter_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	return srv.(UserServerHandler).Info(ctx, in)
}

var UserRouter_Desc = runtime.RouterDesc{
	ServiceName: "jj.wms.User",
	Methods: []runtime.MethodDesc{
		{
			Name:    "Login",
			Method:  "POST",
			Path:    "api/v1/login",
			Handler: _UserRouter_Login_Handler,
		},
		{
			Name:    "Info",
			Method:  "GET",
			Path:    "api/v1/info",
			Handler: _UserRouter_Info_Handler,
		},
	},
}
